method: random
metric:
  name: valid_dataset_iou
  goal: maximize
parameters:
  batch_size:
    values: [4, 8, 16, 32, 63, 128]
  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
  architecture:
    value: "FPN"
  encoder:
    value: "resnet34"
  in_channels:
    value: 3
  out_classes:
    value: 1
early_terminate:
  type: hyperband
  eta: 2
  min_iter: 3
